version: '3.8'

services:
  php-app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html  # Maps current dir to Apache root
    depends_on:
      - mysql  # Must match the service name below

  mysql:  # <- This name becomes the hostname "mysql"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  # Must match PHP code
      MYSQL_DATABASE: gestion_absence
    volumes:
      - ./gab.sql:/docker-entrypoint-initdb.d/init.sql